project:
  type: book

execute: 
  freeze: auto

book:
  title: "Ray-Tracing in Rust"
  author:
    - name: "Dexter Chen"
      email: "dexterccc@126.com"
  date: today
  description: "Build a PBRT-like renderer in Rust."
  url: https://noau.github.io/rtir-book
  repo-url: https://github.com/noau/rtir-book
  repo-actions: issue
  license: "CC BY-NC-ND"
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: part1-basic/part1.qmd
      chapters:
        - part1-basic/setup-project.qmd
        - part1-basic/geo-colors.qmd
        - part1-basic/film.qmd
        - part1-basic/brute-rendering.qmd
        - part1-basic/improve-cli.qmd
        - part1-basic/transformations.qmd
        - part1-basic/metal-dieletric.qmd
        - part1-basic/simple-bvh.qmd
        - part1-basic/naive-light.qmd
        - part1-basic/quad-cube.qmd
        - part1-basic/simple-uv.qmd
    - part: part2-pbr/part2.qmd
      chapters:
        - part2-pbr/simple-bsdf.qmd
  appendices:
    - references.qmd
  page-footer:
    center: 
      - text: "© 2024 Dexter Chen. All Rights Reserved."

filters:
  - social-share
  - collapse-callout

share:
  location: "before-body"
  permalink: "https://noau.github.io/rtir-book"
  description: "Build a PBRT-like renderer in Rust."
  twitter: true
  facebook: true
  reddit: true
  stumble: true
  tumblr: true
  linkedin: true
  email: true
  mastodon: true

collapse-callout:
  all: false
callout-appearance: simple
callout-icon: true

bibliography: references.bib

format:
  bookup-html:
    toc: true
    toc-depth: 3
    code-line-numbers: true
